export const CLIENTS = [
	{ name: "Adobe", url: "https://adobe.com/" },
	{ name: "Arena AI", url: "https://arena-ai.com/" },
	{ name: "Assembled", url: "https://assembled.com/" },
	{ name: "Better", url: "https://better.com/" },
	{ name: "Candy", url: "https://candy.com/" },
	{ name: "Coast", url: "https://coastpay.com/" },
	{ name: "Feather", url: "https://livefeather.com/" },
	{ name: "FourSquare", url: "https://foursquare.com/" },
	{ name: "Frame.io", url: "https://frame.io/" },
	{ name: "Grammarly", url: "https://grammarly.com/" },
	{ name: "Headway", url: "https://headway.co/" },
	{ name: "Mantra Health", url: "https://mantrahealth.com/" },
	{ name: "Moda Operandi", url: "https://modaoperandi.com/" },
	{ name: "Genius", url: "https://genius.com/" },
	{ name: "Warby Parker", url: "https://warbyparker.com/" },
]