export const CLIENTS = [
	{ name: "Adobe", url: "https://adobe.com/" },
	{ name: "Affirm", url: "https://affirm.com/" },
	{ name: "Arena AI", url: "https://arena-ai.com/" },
	{ name: "Assembled", url: "https://assembled.com/" },
	{ name: "Better", url: "https://better.com/" },
	{ name: "Blackbird", url: "https://blackbird.xyz/" },
	{ name: "Candy", url: "https://candy.com/" },
	{ name: "Coast", url: "https://coastpay.com/" },
	{ name: "Feather", url: "https://livefeather.com/" },
	{ name: "Forme", url: "https://formefinancial.com/" },
	{ name: "FourSquare", url: "https://foursquare.com/" },
	{ name: "Frame.io", url: "https://frame.io/" },
	{ name: "Grammarly", url: "https://grammarly.com/" },
	{ name: "Headway", url: "https://headway.co/" },
	{ name: "Kaiyo", url: "https://kaiyo.com/" },
	{ name: "Mantra Health", url: "https://mantrahealth.com/" },
	{ name: "Moda Operandi", url: "https://modaoperandi.com/" },
	{ name: "Rap Genius", url: "https://genius.com/" },
	{ name: "Roofstock", url: "https://roofstock.com/" },
	{ name: "ROKT", url: "https://www.rokt.com/" },
	{ name: "Tenet", url: "https://www.tenet.com/" },
	{ name: "TrialSpark", url: "https://www.trialspark.com/" }
	{ name: "Updater", url: "https://www.updater.com/" },
	{ name: "Underdog", url: "https://www.underdogfantasy.com/" },
	{ name: "Vivi", url: "https://www.vivi.io/" },
	{ name: "Warby Parker", url: "https://warbyparker.com/" },
	{ name: "Whatnot", url: "https://whatnot.com/" },
]